#!/bin/bash
# export PULL_REQUESTS_ASSIGNEE=""
export PACKAGE_MANAGER="bundler" #"hex"
# export PROJECT_PATH="sgoncher-dependabot"
# export DIRECTORY_PATH="/"
export GITHUB_ACCESS_TOKEN="722760e6b3cdca1ebd57153d2993426b5cee53bb"
# export AWS_REGION="us-east-1"
# export AWS_PROFILE="new_labs"
# export AWS_ACCESS_KEY_ID="AKIAUXAYGAAR5ZI7CNU7"
# export AWS_SECRET_ACCESS_KEY="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"
